### ISSUE TITLE
Should South really be listed as a requirement?

### ISSUE THREAD

**Issue by andybak** [spookylukey/django-paypal#101]
I'm on Django 1.8. I was a bit surprised to see pip installing django-paypal brought South into my virtualenv.

I'm a touch concerned that there might be code floating about such as:

    try:
        from south.blah import blah
       ...do something
    except ImportError:
        ...do something else...

In any case - I'm not sure you need South to be pulled in automatically - if people use it, they'll already have it.

**Comment by spookylukey** [comment]
If you are on Django < 1.7, you need South, and we also need to specify a South version - >= 1.0 IIRC. If you use an older version, then you'll get errors. So, the reality is:

* If you are on Django < 1.7, you must use South and it must be >= 1.0
* If you are on Django > 1.7 then you don't need South

The problem is that setup.py has no way of specifying either of these. You can't do a "import django", because it might not be installed before django-paypal. In theory using "setup_requires" instead of "install_requires" caters for this, but "setup_requires" does not work.

At some point, we should probably assume that most people have migrated to Django 1.7, and simply document the requirement on South > 1.0 for Django < 1.7, and leave it out of the setup.py script altogether.

**Comment by andybak** [comment]
OK. I've fixed all the places where the mere presence of South caused errors. Unfortunately this means that all apps I use have to switch to using the 'south_migrations' folder naming from South 1.x.

If it still uses 'migrations' as the name then running tests triggers a migration, tries to import South and cause the tests to fail.

However this was going to trip me up sooner or later so it's probably for the best.
