### ISSUE TITLE
any plan for "authorized use of your PayPal account for future payments"

### ISSUE THREAD

**Issue by s2krish** [spookylukey/django-paypal#111]
PayPal seems to have feature to authorize the use of PayPal for future payments. 

1. Customer authorize their account one-time.
2. In future, merchant send invoice and capture amount.

Is there any plan to support this feature?

Thanks

**Comment by spookylukey** [comment]
django-paypal is a small Open Source project where features are contributed by those most motivated to write them. As the maintainer, I review and merge contributions, and also work on bugs/features where they impact my own use of the library, or if they are critical bugs that I find embarrassing to my reputation, but not generally otherwise.

**Comment by spookylukey** [comment]
Closing for reasons described in the project README.
