### ISSUE TITLE
IPN not returning recurring information

### ISSUE THREAD

**Issue by ernestjumbe** [spookylukey/django-paypal#139]
I have implemented subscription payments according to the example provided in the docs. How ever the subscr_signup IPN that is received does not contain information about the recurring payment. I am receiving two IPNs one is for the subscr_signup and the other is for subscr_payment. The actual transaction seems to be registered on both the customer and merchant account cancellation of subscription also appears to be working. Are there any additional steps that need to be taken to make this integration function as expected?

**Comment by spookylukey** [comment]
I don't know much about how this is supposed to work, you'll need to refer to PayPal docs.

The subscription variables are documented here by PayPal - https://developer.paypal.com/webapps/developer/docs/classic/ipn/integration-guide/IPNandPDTVariables/#id091EB080EYK

and are available on the models due to these fields: https://github.com/spookylukey/django-paypal/blob/master/paypal/standard/models.py#L170

Are you saying that there are some fields missing on the Django models? That would be a bug in django-paypal. Is the data being sent by PayPal, but not recorded? That would be a bug in django-paypal. Otherwise, you'll need to refer to PayPal docs - https://developer.paypal.com/docs/classic/paypal-payments-standard/integration-guide/subscribe_buttons/

I have now added the above links to our docs.

**Comment by ernestjumbe** [comment]
Thanks for the feed back. The docs are not too helpful in this case. The only solution I have come across is to set the next payment date manually and during the initial subscription and hopefully when the recurring payment come in for the next month it will contain the date. I haven't been able to test that yet.

**Comment by skru** [comment]
I believe i can confirm that PayPal is not sending the recurring payment details back to django, 

there is no info in the query field.
