### ISSUE TITLE
Way to change the img src of the form button?

### ISSUE THREAD

**Issue by taylorconsulting** [spookylukey/django-paypal#187]
Is there anyway to specify an image source to be used for the form that is rendered?

**Comment by spookylukey** [comment]
I just released version 0.4.0 (and 0.4.1 due to forgetting to add the docs!) which has docs for this now - see http://django-paypal.readthedocs.io/en/latest/settings.html . Note that the docs are only correct for the latest version  - see http://django-paypal.readthedocs.io/en/latest/release_notes.html#version-0-4-0
