### ISSUE TITLE
Paypal notify url webook expecting x-www-form-urlencoded but received application/json from paypal

### ISSUE THREAD

**Issue by bhaskar8088** [spookylukey/django-paypal#241]
Hello,

I integrated django paypal in one of our customer site for subscriptions. Payment happened successfuly but when the notify_url webhook is hit, django-paypal saying it accepts only "application/x-www-form-urlencoded" but paypal sending "application/json".

Any idea whats going on here? Is this a bug or something I missed ?

Thanks

**Comment by spookylukey** [comment]
I don't know what is happening here, paypal should be sending it urlencoded. This sounds like a bug on Paypal's side, or some kind of misconfiguration. If you have more information, please re-open, but for now I'm going to close because this does not sound like a bug in django-paypal, nor anything I can help you with.
