### ISSUE TITLE
Error Detected with Paypal Encrypted Buttons

### ISSUE THREAD

**Issue by src-r-r** [spookylukey/django-paypal#25]
I am using django-paypal with Paypal Standard IPN. I generated a comodo certificate, downloaded the private certificate, and uploaded the public one to paypal. Then I set PAYPAL_PRIVATE_CERT, PAYPAL_PUBLIC_CERT, PAYPAL_CERT, PAYPAL_CERT_ID, and PAYPAL_IDENTITY_TOKEN accordingly. The button generates (seemingly) without error, but when I try to buy something in sandbox mode I'm redirected to the Paypal Sandbox page with the error:

```Error Detected
Error Message

We were unable to decrypt the certificate id.
We were unable to decrypt the certificate id.```

I tried this with an unencrypted button and there seemed to be a problem sending extra data, namely the redirect URL. Any ideas? Thanks.

**Comment by timdawborn** [comment]
Heh, interesting. Somebody else gets this issue as well! I don't use django-paypal's encrypted form wrapper – I do the crypto logic (copy paste) and HTML construction myself as where it's used isn't Django-form friendly.

I posted this question on SO when we first encountered it, but never got any responses. Strangely for us, it first occurred when migrating from Ubuntu 13.10 servers to Ubuntu 14.04, which possibly implies that it's somehow related to OpenSSL version?

http://stackoverflow.com/questions/23043588/encrypted-buttons-not-working-on-ubuntu-14-04

Did you end up solving this problem? It periodically pops up for us still, sometimes with a different error message though. One thing we did that we found helped reduce the frequency at which these appear is to load *anything* via AJAX from PayPal's domain *before* the encrypted form is sent so that the browser session has some `paypal.com` domain cookies set before it processes the payload.
