### ISSUE TITLE
support multiple paypal accounts from one application

### ISSUE THREAD

**Issue by jmordkoff** [spookylukey/django-paypal#77]
I have a need to collect money for multiple clients using a single web site but as far as I can tell, the account information must be in your settings files.

So I plan to convert the settings into a tuple of tuples like settings.databases and have a selector function or parameter. 

Any recommendations/suggestions on how to proceed? I am an experienced programmer (C++ and perl mostly) and I have been using paypal API's for years but I am somewhat new to python.

**Comment by spookylukey** [comment]
What you highlight is an example of a bigger problem in Django-world - that many applications/libraries are effectively singletons, due to their use of global settings.

Fixing this properly is not easy. However, rather than the route you propose, I'd suggest tackling like it this:

For any function that uses `settings.PAYPAL_*`, provide a way to supply the config options directly (e.g. by keyword arguments).

In fact, this has been done already in some cases. If you are using IPN, you'll see you can already use different accounts:

https://django-paypal.readthedocs.org/en/stable/standard/ipn.html

In the example code, you pass in `settings.PAYPAL_RECEIVER_EMAIL`, but you could pass in whatever you want. If you look at the source code for `PayPalPaymentsForm`, you'll see the `business` field has an `initial` value that defaults to the value in `settings`, but you can override at runtime due to the way Django forms work.

I don't know if the same is true for similar functions in the 'pro' app. If not, I'd be open to similar functionality.

So the basic approach is to move away from needing `settings.py` at all - it should be possible to pass all configuration data directly to the code that needs it. `settings.py` will only be used for default values.

**Comment by spookylukey** [comment]
Looking at it more - the `PayPalWPP` class also already has this functionality - you can pass in your own 'params' instead of the default BASE_PARAMS.

These things would ideally be documented!

**Comment by jmordkoff** [comment]
Thanks Luke...I'll dig into it a little and write up what I learn. I guess
I should clone the project and push an update the the doc? Or can I just
send my notes to this list?

JLM



On Mon, Feb 2, 2015 at 10:45 AM, Luke Plant <notifications@github.com>
wrote:

> Looking at it more - the PayPalWPP class also already has this
> functionality - you can pass in your own 'params' instead of the default
> BASE_PARAMS.
>
> These things would ideally be documented!
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/spookylukey/django-paypal/issues/77#issuecomment-72478824>
> .
>



-- 
Jeremy Mordkoff

*Our lives begin to end the day we become silent about things that matter.
 --  Dr.Martin Luther King Jr.*

**Comment by spookylukey** [comment]
The easiest for me is if you:

1) fork the repo on GitHub
2) clone your fork
3) create a branch for your work
4) push your branch to GitHub
5) send me a pull request.

This article seems pretty good if you are new to GitHub: https://gun.io/blog/how-to-github-fork-branch-and-pull-request/

If you are just doing smallish doc updates, you can use the 'edit' button (pencil) that appears in GitHub e.g. here: https://github.com/spookylukey/django-paypal/blob/master/docs/install.rst

This streamlines the above process. However, for longer doc updates, it doesn't always work well, because you really need to check that the docs build correctly with Sphinx.

Thanks!

**Comment by spookylukey** [comment]
Closing for reasons described in the project README
