### ISSUE TITLE
multi-byte character doesn't allowed in item_name.

### ISSUE THREAD

**Issue by shinriyo** [spookylukey/django-paypal#87]
I used IPN's PayPalPaymentsForm.
I put item_name in multi-byte string.
ex) Japanese.

```
    paypal_dict = {
        "business": settings.PAYPAL_RECEIVER_EMAIL,
        # "item_name": unicode(name,'utf-8'),
        "item_name": name, # multi-byte string
        # something
    }

    form_plan = PayPalPaymentsForm(initial=paypal_dict)
    # something
```

Later, I checked in  PayPal IPNs table in django databse.
The writing is garbled in item_name column.

`unicode(name,'utf-8'),` couldn't work.

Could you tell me how to fix name of item_name?
Or I should modify code of django-paypal?

![multibyte](https://cloud.githubusercontent.com/assets/396927/6704385/f16dc146-cd8a-11e4-8014-3dab76fa4042.png)

**Comment by spookylukey** [comment]
Without knowing the exact bytes you have stored, I don't know how to fix your problem.

There is no such thing as a "multi-byte string" in Python terminology, so I don't know what you mean. There are only:

* unicode strings (series of Unicode code points). This is what Django and django-paypal use internally, and what it sends to the database.
* byte strings (series of bytes, usually obtained by taking a unicode string and encoding using a specified encoding e.g. UTF-8). Byte strings are needed for communicating over HTTP, because the internet only knows about bytes.

django-paypal is designed to work with unicode strings internally, and will correctly decode byte strings received from PayPal.  It is possible it has bugs when creating byte strings to PayPal - I'll need to check.

**Comment by spookylukey** [comment]
I've looked into this, and it is due to default settings on PayPal. I can successfully pass Japanese characters to PayPal:

    # -*- coding: utf-8 -*-
    from __future__ import unicode_literals

         paypal_dict = {
           # ...
            "item_name": "々仝 ± Camp plâcé booking",
        }

(random unicode chars, plus normal, plus some Japanese).

Result:

![screenshot from 2015-06-10 17 29 13](https://cloud.githubusercontent.com/assets/62745/8088172/4f7577ea-0f97-11e5-8193-0f6c453c8499.png)

However, when the data comes back, the Japanese characters have been converted to `"\x1a"`.

It turns out that this is because PayPal has a default charset for your account of "windows-1252", which doesn't support Japanese characters.

To fix this, you need to edit your PayPal settings:

Log on to your account. Assuming you have the new interface:
Choose Profile (top right) -> Profile and Settings -> My selling preferences -> PayPal button language encoding -> More options

Choose 'UTF-8' from the encoding menu and 'Yes' to the next question.

With this done, Japanese characters do indeed come back correctly:

![screenshot from 2015-06-10 17 45 56](https://cloud.githubusercontent.com/assets/62745/8088365/a841a794-0f98-11e5-97a1-044a2053bf44.png)
