### ISSUE TITLE
Encrypted button Python3.4

### ISSUE THREAD

**Issue by Linn9** [spookylukey/django-paypal#90]
Hello,
I can't use the encrypted button, because M2Crypto doesn't work with my Python3 on Ubuntu. I've a other alternative for that ?

PS: Sorry for my english.

**Comment by spookylukey** [comment]
I don't know of any alternatives I'm afraid.

You main options are:
* investigate the possibility of using Python 2 instead of Python 3. There is no reason why you can't install Python 2 in a virtualenv even if Python 3 is the default, although it may take a bit of work.
* work on adding Python 3 support to M2Crypto. However, M2Crypto doesn't look very well maintained - this might be a challenge.
