### ISSUE TITLE
IPN dates are parsed w/o timezone information

### ISSUE THREAD

**Issue by rafacarrascosa** [spookylukey/django-paypal#92]
While playing with IPN I've noticed that the field `payment_date` was POSTed with value `'16:23:34 May 05, 2015 PDT'` and parsed as ` datetime.datetime(2015, 5, 5, 16, 23, 34, tzinfo=<UTC>)`, ie: ignoring the timezone specified in the string.

I'm a django newbie, but perhaps this can be fixed by using the `input_formats`argument of `DateTimeField` in [here](https://github.com/spookylukey/django-paypal/blob/master/paypal/standard/models.py#L105), right?

Also, this issue may also apply to fields `auction_closing_date`, `next_payment_date`, `time_created`, `retry_at`, `subscr_date`, `subscr_effective` and `case_creation_date`

**Comment by spookylukey** [comment]
`models.DateTimeField` doesn't support `input_values`, only `forms.DateTimeField` - https://docs.djangoproject.com/en/1.8/ref/forms/fields/#django.forms.DateField.input_formats

We are already using that. However, it doesn't support timezone parsing, probably because the underlying library (`datetime.datetime.strptime`) doesn't support it - https://docs.python.org/2/library/datetime.html#datetime.datetime.strptime

I do have some alternative ideas for fixing this though.

**Comment by rafacarrascosa** [comment]
Great!
As I said, I'm a Django newbie so I'm quite confident that your alternative is much better.

**Comment by spookylukey** [comment]
This is fixed in 0.2.4. There is a migration documented if you want to fix your old data: http://django-paypal.readthedocs.org/en/latest/release_notes.html#version-0-2-4

**Comment by rafacarrascosa** [comment]
Thanks Luke!

**Comment by spookylukey** [comment]
There is another PR I missed, with other date fields that have the problem:

https://github.com/spookylukey/django-paypal/pull/95/files

So you might want to wait until I address that before upgrading
